version: "3.8"

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
      - "3001:3001"